### ISSUE TITLE
Apple Music user token

### ISSUE THREAD

**Issue by maddestscooter** [Rohan-cod/Music_Playlist#11]
Is it possible to have a guide on how to generate the Apple Music user token via Python? Thanks.

**Comment by Rohan-cod** [comment]
Yes, you can work on that. Add it to the [Readme.md](https://github.com/Rohan-cod/Music_Playlist/blob/master/README.md) file.

**Comment by maddestscooter** [comment]
I wish I could. I have tried generating a valid user token without any luck. So I am hoping to have the guide for myself!

**Comment by Rohan-cod** [comment]
@maddestscooter, you should ask before opening an issue. You could have emailed me or asked on slack. You opened an issue and you yourself don't know how to resolve it. I'll add the steps to generate an Apple Music User token soon.

**Comment by maddestscooter** [comment]
Isn't this what issues are for in Github, questions and suggestions? I had sent you an email a few weeks ago as well...

**Comment by Rohan-cod** [comment]
You are right, issues are for questions and suggestions. But, you cannot open an issue on someone else's repository without their permission. We have community channels like slack for that. The link to join the channel is available in the readme and also on the KWoC website. If you have questions or suggestions you can ask them on the channel itself. And if you want to open an issue, you must ask the maintainer of the repository first. I hope you get the point.

**Comment by maddestscooter** [comment]
The slack link is given on the readme returns 'This link is no longer active'

**Comment by Rohan-cod** [comment]
I have updated the link. It will work now.
