### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jaisai6** [Rohan-cod/Music_Playlist#9]
Update the README by adding the step by step procedure on how to get the OAuth credentials from Youtube(screenshots can be used for clear understanding). Also, add a note regarding the KeyValue Error (which occurs due to the Expired Spotify token).
Add a new point in the "Setting up the project" regarding the deployment of the app.

**Comment by jaisai6** [comment]
@Rohan-cod can you assign this issue to me.

**Comment by Rohan-cod** [comment]
Issue resolved.
@jaisai6's pull request(#10 ) was merged.
